# ignore release tags
if: tag IS blank

env:
  global:
    - CC_TEST_REPORTER_ID=9c6558805c8a00ef83371f4dcd82bfc765d2eac147a7442164f8cc1b401d43de

cache:
  directories:
    - /home/travis/.cache/yarn

language: node_js
node_js:
  - "node"

install:
  - npm install -g yarn@latest
  - npm run bootstrap
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npx _check_deps
  - npm run tsc_lint_test
  - git checkout -f
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_deploy:
  - pushd $HOME
  - openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
    -in $TRAVIS_BUILD_DIR/.travis/secrets.tar.enc -out secrets.tar -d
  - tar -xvf secrets.tar
  - popd
deploy:
  - provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    env:
      secure: JDw06YX4/egO+WjuWVHsEcPS/04syh6fEpY1RbQgEypFNDt8UVvHXPcSP6nNp2YDvfbAWF1TBKojBJk02EQDB1KlQgnO/csvq3tBOSlQU0Cku6zKcUX6LzywLuBPfc3gYKTeXsiNly31vmMxTh2hwHnx2iYxHdMN7CojQpf1JdI=
    on:
      branch: [latest, next]
      repo: taye/interact.js
